### ISSUE TITLE
DBZ mod Conflict or bug

### ISSUE THREAD

**Issue by Ashtar084** [Arrenton/Leveled#16]
Hi, I play this with DBZ mod, updated the dragon ball today and I received this message of your mod what can it be?
please help

Field not found: 'DBZMOD.MyPlayer.KiDamage'.
in Leveled.LeveledMain.HookDBZPlayerVar(String Var, Int32 player, Boolean modify, Double newVal)
in Leveled.Players.PlayerMod.SupportModStats() na C:\Users\gotes\Documents\My Games\Terraria/ModLoader\Mod Sources\Leveled\Player\PlayerMod.cs:linha 2225
in Leveled.Players.PlayerMod.PreUpdateMovement() na C:\Users\gotes\Documents\My Games\Terraria/ModLoader\Mod Sources\Leveled\Player\PlayerMod.cs:linha 2286
in Terraria.ModLoader.PlayerHooks.PreUpdateMovement(Player player)
in Terraria.Player.Update(Int32 i)
in Terraria.WorldGen.do_playWorldCallBack(Object threadContext)
in Terraria.WorldGen.playWorldCallBack(Object threadContext) 👍

🗡
I'm sorry if it's not here that advertises this kind of bug, but I do not find any other place

**Comment by webmilio** [comment]
This is indeed where you post the issue. You obviously didn't follow the example issue, however. For future reference, check https://github.com/Arrenton/Leveled/issues/1.

This issue is already known by both Leveled and DBT developers. I'm currently working on DBT at the same time, so I can tell you there should be a fix for it soon. Just waiting to hotfix DBT.
